### ISSUE TITLE
محدود کردن نمایش فعالیت ها بر اساس زمان

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#12]
همون دکمه هایی بود که گذاشتی بدش برداشتی!؟ 
میخواد یه جوری محدود کنه نمایش فآلیت ها رو. ینی مثلن فآلیت‌هایی که از ۲۵ بهمن به بد هست رو نمایش بده!؟

**Comment by me2bits** [comment]
اینو صحبت کردم قرار شد توی آدرس بار برامون بذارند و ما به سرور بفرستیمم و خودشون فعالیت هایی که توی اون بازه هست رو فقط بفرستند.
پس نام استارت و اند رو توی آدرس بار تیین کن و توی داکیومنت وب سرویست بیار و توی وب سروی هم حواست باشه که ارسال کنی.‏
تشکر

**Comment by amirhoseinaliakbarian** [comment]
https://github.com/amirhoseinaliakbarian/ext.gantt/commit/0ac346a2ce7358d2e97a81c949059d3306767d23

پارامترهای
StartDate
 و 
EndDate
از آدرس گرفته می‌شه در هر دوی لود و سینک به همین نام ارسال می‌شه.
