### ISSUE TITLE
جابه‌جایی

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#14]
در تب پیشرفته
از قسمت روش محاسبه پیشرفت به بد رو بیار توی تب امومی زیر محاسبه پیشرفت
و اگر ممکنه اوناییش که با هم هستند کنار هم باشند که اسکرول نخوره! مثل نفر ساات کل و نفر ساات انجام شده توی یه سطر باشه تا زیر هم

**Comment by amirhoseinaliakbarian** [comment]
https://github.com/amirhoseinaliakbarian/ext.gantt/commit/0ac346a2ce7358d2e97a81c949059d3306767d23
