### ISSUE TITLE
رنگ

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#3]
وقتی روی نمودار راست کلیک کرده و رنگ را تغییر می دهم فقط بخشی از رنگ تغییر می‌کند... بقیه اش رو باید چگونه تغییر دهم!؟

**Comment by amirhoseinaliakbarian** [comment]
اون قسمتش که عوض نمی‌شه، بخش انجام شده‌ی پروژه‌س! اون قابل تغییر نیست!

Date: Fri, 20 May 2016 10:13:53 -0700

**Comment by me2bits** [comment]
هماهنگه!‏

**Comment by me2bits** [comment]
پس چرا راست به چپ نیست!

**Comment by amirhoseinaliakbarian** [comment]
چی راست به چپ نیست؟! خب پروژه به صورت عادی اون رنگیه که تو مشخص می‌کنی. بعدش هرچی انجام بشه، از سمت راست پر می‌شه دیگه!

Date: Sat, 21 May 2016 04:58:48 -0700

**Comment by me2bits** [comment]
رنگ بایستی حتما به سمت سرور ارسال شود

**Comment by amirhoseinaliakbarian** [comment]
اگر تغییر کرده باشد، ارسال می‌شود!
