### ISSUE TITLE
ادیتور یادداشت

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#5]
راست چین چپ چین و به طور کلی دکمه ها صحیح و درست شوند.
در ابتدا کرسر ملوم نیست!‏
فونت حتما اضافه شود و پیش فرض انتخاب شده باشد

**Comment by amirhoseinaliakbarian** [comment]
https://github.com/amirhoseinaliakbarian/ext.gantt/commit/d017b1bd77d0e0063725e9a48a485c855cdc15ee
