### ISSUE TITLE
وظیفه -> فاز/فعالیت...‏

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#6]
کلمه اطلاعات وظیفه به اطلاعات فاز/وظیفه...‏ تبدیل شود
سه نقطه هم نداشت طوری نیست

**Comment by amirhoseinaliakbarian** [comment]
https://github.com/amirhoseinaliakbarian/ext.gantt/commit/d017b1bd77d0e0063725e9a48a485c855cdc15ee
