### ISSUE TITLE
نام پروژه -> نام فعالیت

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#8]
در قسمت سمت راست، بالای فعالیت ها که امکان جست و جو هم هست باید نام پروژه به نام فعالیت تغییر کند

**Comment by amirhoseinaliakbarian** [comment]
https://github.com/amirhoseinaliakbarian/ext.gantt/commit/d017b1bd77d0e0063725e9a48a485c855cdc15ee
