### ISSUE TITLE
جست‌وجو

### ISSUE THREAD

**Issue by me2bits** [amirhoseinaliakbarian/ext.gantt#9]
جست‌و‌جو درست کار نمی کنه.
کلمه مرحله کار می کنه ولی ساخت خیر
حدس:
ظاهرا فقط توی برگ ها جست و جو می کند.
درضمن وقتی مرحله را سرچ می کنی دقت کن که راست چین نبودن چقدر زشتش می کنه مثلا ساخت نمونه اولیه زیر فاز پیاده سازی هست ولی به دلیل طول زیاد کلمه هاش تو رفتگیش درست نیست!‏
کلن چرا این ستون راست چین نیست؟راست به چپ و راست چین باید بشه ... بقیه ستون ها که هست!؟

**Comment by me2bits** [comment]
please fix this issue.
it's important to fix CSS problem.....

**Comment by amirhoseinaliakbarian** [comment]
https://github.com/amirhoseinaliakbarian/ext.gantt/commit/ce40178eb57b210f36d7bc213d6ea2769a549c64
مسئله‌ی سی‌اس‌اس حل شد. اما خود سرچ هنوز نه.

**Comment by me2bits** [comment]
body p { margin-bottom: 0cm; margin-top: 0pt; } 
  
  
    سرچ رو که گفتم چیکار گنی!

**Comment by amirhoseinaliakbarian** [comment]
گفتی، ولی همون هم کشکی که نیست که

Date: Wed, 25 May 2016 03:03:34 -0700

**Comment by me2bits** [comment]
میدونم کشکی نیست! ولی شما استادید ... شما خفنید :+1:
